apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
    }

    defaultConfig {
        applicationId "com.aditya1962.RealTimeHomeTheftDetect.theftdetection"

        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        Properties localProperties = new Properties()
        File localPropertiesFile = rootProject.file('local.properties')
        if (localPropertiesFile.exists()) {
            localProperties.load(new FileInputStream(localPropertiesFile))
        }

        // Fetch from properties file, fallback to environment variable, or use empty string
        String dbUrl = localProperties.getProperty("DATABASE_URL")
        if (dbUrl == null) {
            dbUrl = System.getenv("DATABASE_URL")
        }
        if (dbUrl == null) {
            dbUrl = '""' // Fallback to safe empty string
        }

        // Inject the configuration into the generated BuildConfig class
        buildConfigField "String", "DATABASE_URL", dbUrl
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.0'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.google.firebase:firebase-database:9.0.2'
    compile 'com.google.firebase:firebase-storage:9.0.2'
    compile 'com.firebase:firebase-client-android:2.5.0'
    compile 'com.google.firebase:firebase-core:9.0.1'
    compile 'com.google.android.gms:play-services-vision:9.0.2'
    compile 'com.google.android.gms:play-services-appindexing:9.0.2'
}

apply plugin: 'com.google.gms.google-services'